# Website configuration
title = "viral32111's website"
baseURL = "https://viral32111.com"

[language]
locale = "en-gb"

# Do not place pages in their own directories
uglyURLs = false

# Allow fetching file modification times from Git, for use below
enableGitInfo = true

# Try use file modification times from Git, falling back to front matter, then filesystem, and finally build time
[frontmatter]
lastmod = [ "lastmod", ":git", ":fileModTime", ":default" ]

# Custom parameters
[params]
authorName = "viral32111"
authorEmailAddress = "contact@viral32111.com"
searchTags = "viral32111,conspiracy servers,brother gaming,programmer,programming,developer,developing,coding,freelance,community"
themeColor = "#AEA49A" # Majority color of my avatar

# Disable taxonomies
[taxonomies]
tag = ""
category = ""

[minify]
minifyOutput = true
disableHTML = false
disableCSS = false
disableJS = true

[minify.tdewolff.html]
keepComments = false
keepSpecialComments = true
keepDefaultAttrVals = true
keepDocumentTags = true
keepEndTags = true
keepQuotes = true
keepWhitespace = true

[minify.tdewolff.css]
version = 0
precision = 0

[outputs]
home = ["html", "sitemap", "robots"]

[outputFormats.sitemap]
mediaType = "text/plain"
baseName = "sitemap"
isPlainText = true

[outputFormats.robots]
mediaType = "text/plain"
baseName = "robots"
isPlainText = true

# https://gohugo.io/quick-reference/syntax-highlighting-styles/
[markup.highlight]
noClasses = false
style = "friendly"

lineNos = true
lineNumbersInTable = false
