# Website configuration
title = "viral32111's website"
baseURL = "https://viral32111.com"
languageCode = "en-gb"

# Allow fetching file modification times from Git, for use below.
enableGitInfo = true

# Try use file modification times from Git, falling back to front matter, then filesystem, and finally build time.
[frontmatter]
lastmod = [ "lastmod", ":git", ":fileModTime", ":default" ]

# Custom parameters.
[params]
authorName = "viral32111"
authorEmailAddress = "contact@viral32111.com"
searchTags = "viral32111,conspiracy servers,brother gaming,programmer,programming,developer,developing,coding,freelance,community"
themeColor = "#AEA49A" # Majority color of my avatar

# Disable taxonomies
[taxonomies]
tag = ""
category = ""

[minify]
minifyOutput = true
disableHTML = false
disableCSS = false
disableJS = true

[minify.tdewolff.html]
keepComments = false
keepConditionalComments = true
keepDefaultAttrVals = true
keepDocumentTags = true
keepEndTags = true
keepQuotes = true
keepWhitespace = true

[minify.tdewolff.css]
keepCSS2 = false # Not like we support ancient browsers anyway due to the security requirements
precision = 0
