# Security enhancing headers
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
add_header Content-Security-Policy "default-src 'none'; base-uri 'self'; style-src 'self'; script-src 'self'; img-src 'self'; media-src 'self'; frame-ancestors 'none'; form-action 'none'; upgrade-insecure-requests;" always;
add_header Referrer-Policy "same-origin" always;
add_header X-Content-Type-Options "nosniff" always;
add_header X-Frame-Options "DENY" always;
# add_header X-XSS-Protection "0" always;

# Inform Tor Browser visitors of the hidden service on successful responses
# add_header Onion-Location "http://viraldwfella5we7pdbi75pmzg4bcrehcwjstyy6tgjbqhdh6pgdi6yd.onion$request_uri";

# Prevent page archiving & image indexing
add_header X-Robots-Tag "noarchive, noimageindex";
